import Head from 'next/head'
import React from 'react'
import HeaderLayout from './header/layout'

const breadcrumbs = ['about']

const Index: React.FunctionComponent = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <HeaderLayout breadcrumbs={breadcrumbs} />
      <main className='wrapper'>
        <p>
          I am a web master, artist, and licensed
          bodyworker. I’ve built tools and taught creativity
          at <a href='http://adobe.com'>Adobe</a> and{' '}
          <a href='http://kano.me'>Kano Computing</a>, and
          managed mobile healthcare at{' '}
          <a href='http://mindoktor.se'>Min Doktor</a>.
        </p>
        <p>
          Currently I am between Los Angeles and London,
          building the future of interface design with{' '}
          <a href='https://utopia.app'>Utopia</a> 🤙.
        </p>
      </main>
    </>
  )
}
export default Index
